// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportSchedule.Context;

#nullable disable

namespace SportSchedule.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20250728075025_update League table")]
    partial class updateLeaguetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportSchedule.Model.AccountModel", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.AwardModel", b =>
                {
                    b.Property<int>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AwardId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Gift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GuessId")
                        .HasColumnType("integer");

                    b.HasKey("AwardId");

                    b.HasIndex("GuessId")
                        .IsUnique();

                    b.ToTable("Award", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.CardModel", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("valid");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.Property<string>("TypeCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Card Yellow");

                    b.HasKey("CardId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Card", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.CommentModel", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("CommendIdReply")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 7, 28, 7, 50, 24, 527, DateTimeKind.Utc).AddTicks(5590));

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId");

                    b.HasIndex("CommendIdReply");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.GoalModel", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GoalId"));

                    b.Property<DateTime>("GoalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoalType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Nomal");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("GoalId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Goal", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.GuessModel", b =>
                {
                    b.Property<int>("GuessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GuessId"));

                    b.Property<DateTime?>("GuessTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 7, 28, 7, 50, 24, 593, DateTimeKind.Utc).AddTicks(4048));

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("PredictAwayScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("PredictHomeScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GuessId");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Guess", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.LeagueModel", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeagueId");

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.LeagueSeasonModel", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId", "SeasonId");

                    b.HasIndex("SeasonId");

                    b.ToTable("LeagueSeason", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.LeagueTeamModel", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("LeagueTeam", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.MatchModel", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchId"));

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Chưa đá");

                    b.Property<int?>("TeamIdAway")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamIdHome")
                        .HasColumnType("integer");

                    b.Property<string>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("07/28/2025 07:50:24");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MatchId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamIdAway");

                    b.HasIndex("TeamIdHome");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.MatchStatictisModel", b =>
                {
                    b.Property<int>("MatchStatictisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchStatictisId"));

                    b.Property<int?>("Corners")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Possession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("50");

                    b.Property<int?>("RedCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("0");

                    b.Property<int?>("ShortsOnTaget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("YellowCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("MatchStatictisId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchStatictis", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.MemberModel", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MemberId");

                    b.ToTable("Member", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SportSchedule.Model.MessageModel", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SendTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 7, 28, 7, 50, 24, 532, DateTimeKind.Utc).AddTicks(3257));

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("string");

                    b.Property<int?>("UserIdRevice")
                        .HasColumnType("integer");

                    b.Property<int?>("UserIdSend")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("UserIdRevice");

                    b.HasIndex("UserIdSend");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.PeriodModel", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodId"));

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PeriodId");

                    b.HasIndex("MatchId");

                    b.ToTable("Period", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.PostModel", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2025, 7, 28, 7, 50, 24, 514, DateTimeKind.Utc).AddTicks(2541));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.RankingModel", b =>
                {
                    b.Property<int>("RankingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankingId"));

                    b.Property<int>("Draw")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalDifference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalsFor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("Loss")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Played")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Point")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Win")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("RankingId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamId");

                    b.ToTable("Ranking", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.SeasonModel", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonId"));

                    b.Property<string>("SeasonYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SeasonId");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.TeamMemberModel", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("MemberId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMember", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.TeamModel", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameHome")
                        .HasColumnType("text");

                    b.Property<int?>("TeamType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("TeamId");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.PlayerModel", b =>
                {
                    b.HasBaseType("SportSchedule.Model.MemberModel");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<bool?>("status")
                        .HasColumnType("boolean");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("SportSchedule.Model.AccountModel", b =>
                {
                    b.HasOne("SportSchedule.Model.UserModel", "User")
                        .WithOne("Account")
                        .HasForeignKey("SportSchedule.Model.AccountModel", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSchedule.Model.AwardModel", b =>
                {
                    b.HasOne("SportSchedule.Model.GuessModel", "Guess")
                        .WithOne("Award")
                        .HasForeignKey("SportSchedule.Model.AwardModel", "GuessId");

                    b.Navigation("Guess");
                });

            modelBuilder.Entity("SportSchedule.Model.CardModel", b =>
                {
                    b.HasOne("SportSchedule.Model.PeriodModel", "Period")
                        .WithMany("Cards")
                        .HasForeignKey("PeriodId");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("SportSchedule.Model.CommentModel", b =>
                {
                    b.HasOne("SportSchedule.Model.CommentModel", "Comment")
                        .WithMany("Comments")
                        .HasForeignKey("CommendIdReply")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportSchedule.Model.PostModel", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.HasOne("SportSchedule.Model.UserModel", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSchedule.Model.GoalModel", b =>
                {
                    b.HasOne("SportSchedule.Model.PeriodModel", "Period")
                        .WithMany("Goals")
                        .HasForeignKey("PeriodId");

                    b.HasOne("SportSchedule.Model.PlayerModel", "Player")
                        .WithMany("Goals")
                        .HasForeignKey("PlayerId");

                    b.HasOne("SportSchedule.Model.TeamModel", "Team")
                        .WithMany("Goals")
                        .HasForeignKey("TeamId");

                    b.Navigation("Period");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportSchedule.Model.GuessModel", b =>
                {
                    b.HasOne("SportSchedule.Model.MatchModel", "Match")
                        .WithMany("Guess")
                        .HasForeignKey("MatchId");

                    b.HasOne("SportSchedule.Model.UserModel", "User")
                        .WithMany("Guess")
                        .HasForeignKey("UserId");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSchedule.Model.LeagueSeasonModel", b =>
                {
                    b.HasOne("SportSchedule.Model.LeagueModel", "League")
                        .WithMany("LeagueSeasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportSchedule.Model.SeasonModel", "Season")
                        .WithMany("LeagueSeasons")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SportSchedule.Model.LeagueTeamModel", b =>
                {
                    b.HasOne("SportSchedule.Model.LeagueModel", "League")
                        .WithMany("LeagueTeams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportSchedule.Model.TeamModel", "Team")
                        .WithMany("LeagueTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportSchedule.Model.MatchModel", b =>
                {
                    b.HasOne("SportSchedule.Model.LeagueModel", "League")
                        .WithMany("Matchs")
                        .HasForeignKey("LeagueId");

                    b.HasOne("SportSchedule.Model.SeasonModel", "Season")
                        .WithMany("Matchs")
                        .HasForeignKey("SeasonId");

                    b.HasOne("SportSchedule.Model.TeamModel", "TeamAway")
                        .WithMany("MatchTeamAways")
                        .HasForeignKey("TeamIdAway");

                    b.HasOne("SportSchedule.Model.TeamModel", "TeamHome")
                        .WithMany("MatchTeamHomes")
                        .HasForeignKey("TeamIdHome");

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("TeamAway");

                    b.Navigation("TeamHome");
                });

            modelBuilder.Entity("SportSchedule.Model.MatchStatictisModel", b =>
                {
                    b.HasOne("SportSchedule.Model.MatchModel", "Match")
                        .WithMany("MatchStatictis")
                        .HasForeignKey("MatchId");

                    b.HasOne("SportSchedule.Model.TeamModel", "Team")
                        .WithMany("MatchStatictis")
                        .HasForeignKey("TeamId");

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportSchedule.Model.MessageModel", b =>
                {
                    b.HasOne("SportSchedule.Model.UserModel", "UserRevice")
                        .WithMany("MessageRevices")
                        .HasForeignKey("UserIdRevice");

                    b.HasOne("SportSchedule.Model.UserModel", "UserSend")
                        .WithMany("MessageSends")
                        .HasForeignKey("UserIdSend");

                    b.Navigation("UserRevice");

                    b.Navigation("UserSend");
                });

            modelBuilder.Entity("SportSchedule.Model.PeriodModel", b =>
                {
                    b.HasOne("SportSchedule.Model.MatchModel", "Match")
                        .WithMany("Periods")
                        .HasForeignKey("MatchId");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SportSchedule.Model.PostModel", b =>
                {
                    b.HasOne("SportSchedule.Model.UserModel", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSchedule.Model.RankingModel", b =>
                {
                    b.HasOne("SportSchedule.Model.LeagueModel", "League")
                        .WithMany("Rankings")
                        .HasForeignKey("LeagueId");

                    b.HasOne("SportSchedule.Model.TeamModel", "Team")
                        .WithMany("Rankings")
                        .HasForeignKey("TeamId");

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportSchedule.Model.TeamMemberModel", b =>
                {
                    b.HasOne("SportSchedule.Model.MemberModel", "Member")
                        .WithMany("TeamMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportSchedule.Model.TeamModel", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SportSchedule.Model.UserModel", b =>
                {
                    b.HasOne("SportSchedule.Model.RoleModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SportSchedule.Model.PlayerModel", b =>
                {
                    b.HasOne("SportSchedule.Model.MemberModel", null)
                        .WithOne()
                        .HasForeignKey("SportSchedule.Model.PlayerModel", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportSchedule.Model.CommentModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SportSchedule.Model.GuessModel", b =>
                {
                    b.Navigation("Award");
                });

            modelBuilder.Entity("SportSchedule.Model.LeagueModel", b =>
                {
                    b.Navigation("LeagueSeasons");

                    b.Navigation("LeagueTeams");

                    b.Navigation("Matchs");

                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("SportSchedule.Model.MatchModel", b =>
                {
                    b.Navigation("Guess");

                    b.Navigation("MatchStatictis");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SportSchedule.Model.MemberModel", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("SportSchedule.Model.PeriodModel", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SportSchedule.Model.PostModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SportSchedule.Model.RoleModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SportSchedule.Model.SeasonModel", b =>
                {
                    b.Navigation("LeagueSeasons");

                    b.Navigation("Matchs");
                });

            modelBuilder.Entity("SportSchedule.Model.TeamModel", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("LeagueTeams");

                    b.Navigation("MatchStatictis");

                    b.Navigation("MatchTeamAways");

                    b.Navigation("MatchTeamHomes");

                    b.Navigation("Rankings");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("SportSchedule.Model.UserModel", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Comments");

                    b.Navigation("Guess");

                    b.Navigation("MessageRevices");

                    b.Navigation("MessageSends");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SportSchedule.Model.PlayerModel", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
